apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-app
  namespace: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: html-app
  template:
    metadata:
      labels:
        app: html-app
    spec:
      containers:
      - name: html-app
        image: localhost:5000/html-app:latest
        ports:
        - containerPort: 80